package swing_kontrol;

import javax.swing.JOptionPane;

/**
 *
 * @author sekaist
 */
public class check_box_kontrol extends javax.swing.JFrame {

    /**
     * Creates new form check_box_kontrol
     */
    public check_box_kontrol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        check_oracle = new javax.swing.JCheckBox();
        check_java = new javax.swing.JCheckBox();
        check_python = new javax.swing.JCheckBox();
        btnYorumla = new javax.swing.JButton();
        lblSonuc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        check_oracle.setText("Oracle");

        check_java.setText("Java");
        check_java.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_javaActionPerformed(evt);
            }
        });

        check_python.setText("Python");

        btnYorumla.setText("Yorumla");
        btnYorumla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYorumlaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnYorumla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check_oracle)
                        .addGap(18, 18, 18)
                        .addComponent(check_java)
                        .addGap(18, 18, 18)
                        .addComponent(check_python))
                    .addComponent(lblSonuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_oracle)
                    .addComponent(check_java)
                    .addComponent(check_python))
                .addGap(27, 27, 27)
                .addComponent(btnYorumla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lblSonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnYorumlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYorumlaActionPerformed
        String durum1 = "";
        String durum2 = "";
        String durum3 = "";
        if (check_oracle.isSelected() == true) {
            durum1 = "Oracle DBA";

        }

        if (check_java.isSelected() == true) {
            durum2 = "Java Developer";
        }

        if (check_python.isSelected() == true) {
            durum3 = "Python Geliştiricisi";
        }
        lblSonuc.setText("Tittle:" + " " + durum1 + " " + durum2 + " " + durum3);


    }//GEN-LAST:event_btnYorumlaActionPerformed

    private void check_javaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_javaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_javaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(check_box_kontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(check_box_kontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(check_box_kontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(check_box_kontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new check_box_kontrol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnYorumla;
    private javax.swing.JCheckBox check_java;
    private javax.swing.JCheckBox check_oracle;
    private javax.swing.JCheckBox check_python;
    private javax.swing.JLabel lblSonuc;
    // End of variables declaration//GEN-END:variables
}
